### ISSUE TITLE
Dedicated server log being filled with error

### ISSUE THREAD

**Issue by calloatti** [ModProg/BlockMeter#11]
https://paste.ee/p/O0wJ0

Fabric MC server 1.16.1

blockmeter-1.16.1-fabric0.14.1-1.4.4.jar

**Comment by calloatti** [comment]
The server is new and we are testing everything for now. This only happens when a player uses the feature to display the boxes.

**Comment by ModProg** [comment]
Could you try if using this version on both server and client fixes the Issue, This should be something fixed in the 1.16.2 Version of the mod, which I did not change for the 1.16.1 Version as it does break compatibility other Versions of the Mod for those using the Mod on a Bukkit Server,
[Change zip to jar](https://github.com/ModProg/BlockMeter/files/5143302/blockmeter-1.16.1-fabric0.14.1-1.5.1.zip)
You need to change the `.zip` extension to `.jar` as GitHub does not support `.jar` files here.

**Comment by ModProg** [comment]
If the Issue persist please open another Issue
